[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "Terminess Nerd Font Mono"
size = 9

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500
