#!/bin/sh

DOTFILES_DIR="$HOME/dotfiles"
SCRIPT_DIR="${DOTFILES_DIR}/scripts"
HOME_DIR="${DOTFILES_DIR}/home"
CONFIG_DIR="${DOTFILES_DIR}/config"
FONT_DIR="${DOTFILES_DIR}/fonts"
SCRIPT_FILE="$(find "${SCRIPT_DIR}" -type f -printf '%f ')"
HOME_FILE="$(find "${HOME_DIR}" -type f -printf '%f ')"
CONFIG_FILE="$(find "${CONFIG_DIR}" -mindepth 1 -type d -printf '%f ')"
SHARE_LOCAL_DIR="$HOME/.local/share"

__show_help(){
  cat << EOF
Usage: dotmk [ARGS] [OPTIONS]
Options:
    install,   -i           Install in this dotfiles
    uninstall, -u           Uninstall in this dotfiles
    -h, --help              Show this help
EOF
}

__install(){

  test ! -d "${XDG_CONFIG_HOME}" && mkdir -p "${XDG_CONFIG_HOME}"

  cp -r "${FONT_DIR}" "${SHARE_LOCAL_DIR}"
  
  for file in ${SCRIPT_FILE}
  do
    sudo cp "${SCRIPT_DIR}/$file" /usr/local/bin/
  done

  for file in ${HOME_FILE}
  do
    ln -s "${HOME_DIR}/$file" "$HOME"
  done

  for file in ${CONFIG_FILE}
  do
    ln -s "${CONFIG_DIR}/$file" "${XDG_CONFIG_HOME}"
  done
}

__uninstall(){

  for file in ${SCRIPT_FILE}
  do
    sudo rm -f /usr/local/bin/$file
  done

  for file in ${HOME_FILE}
  do
    rm -f "$HOME/$file"
  done

  for file in ${CONFIG_FILE}
  do
    rm -f "${XDG_CONFIG_HOME}/$file"
  done
}

case "$1" in
  install|-i) __install ;;
  uninstall|-u) __uninstall ;;
  help|-h|--help) __show_help ;;
  *) __show_help ;;
esac
