#!/bin/sh

BAT_DIR="/sys/class/power_supply"
BAT="BAT0"
AC="AC0"

_BAT_capacity(){
  cat ${BAT_DIR}/${BAT}/capacity
}

_BAT_status(){
  BAT_STATUS=$(cat ${BAT_DIR}/${BAT}/status | sed 's/\ //')
  BAT_CAPACITY=$(cat ${BAT_DIR}/${BAT}/capacity)
  if [ ${BAT_STATUS} = "Charging" ]; then
    echo "%{B#a6a305} C+ %{B-}"
  elif [ ${BAT_STATUS} = "Discharging" ]; then
    echo "%{B#424742} D- %{B-}"
  elif [ ${BAT_STATUS} = "Notcharging" -a $((${BAT_CAPACITY})) -ge 99 ]; then
    echo "%{B#086302} FULL %{B-}"
  elif [ $((${BAT_CAPACITY})) -le 25 ]; then
    echo "%{B#820000} D! %{B-}"
  fi
}

_Time(){
  date +%H:%M:%S
}

_Date(){
  date +%D
}

_Layout(){
  xkb-switch -p
}

_Wifi(){
  SSID=$(wpa_cli status | grep -w ssid | sed 's/ssid=//g')
  if [ -z ${SSID} ]; then
    echo "Not Connected"
  else
    echo ${SSID}
  fi
}

_Wifi_RSSI(){
  SSID=$(wpa_cli status | grep -w ssid | sed 's/ssid=//g')
  if [ ${SSID} ]; then
    RSSI=$(( $(wpa_cli signal_poll | grep -w RSSI | sed 's/RSSI=//') ))
    if [ ${RSSI} -gt -50 ]; then
      echo "[||||]"
    elif [ ${RSSI} -ge -60 -a ${RSSI} -le -50 ]; then
      echo "[||| ]"
    elif [ ${RSSI} -ge -70 -a ${RSSI} -le -61 ]; then
      echo "[||  ]"
    elif [ ${RSSI} -lt -70 ]; then
      echo "[|   ]"
    else
      echo " "
    fi
  fi
}

while :
do
  BAR_INPUT="%{c}$(_Date) | $(_Time)%{c}%{r}$(_Layout) | $(_BAT_status) $(_BAT_capacity)%% | $(_Wifi) $(_Wifi_RSSI) %{r}"
  echo $BAR_INPUT
  sleep 1s
done
