#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

dbus-run-session pulseaudio --start &
pgrep -x pa-applet > /dev/null || pa-applet &

killall -q polybar
pgrep -x polybar > /dev/null || polybar --reload top &

~/.fehbg &

setxkbmap -layout us,th -model pc104 -option grp:caps_toggle


bspc monitor -d I II III IV

bspc config focused_border_color '#ffae00'

bspc config border_width         5
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_follows_focus false

# Rule
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Thunar state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating
