#!/bin/env bash

CHOICE=$(printf "poweroff\nreboot\nlockscreen" | dmenu -p "Power ")

if [ -z "$CHOICE" ]; then
  exit 1
fi

case ${CHOICE} in
  "poweroff")
    [[ -n $(command -v loginctl) ]] && loginctl poweroff || sudo poweroff
    ;;
  "reboot")
    [[ -n $(command -v loginctl) ]] && loginctl reboot || sudo reboot
    ;;
  "lockscreen")
    slock
    ;;
esac
