#!/bin/env bash

DIRECTORY="$HOME"'/VM'

CHOICE=$(printf "kali\nmetasploitable" | dmenu -p "VM ")

case "${CHOICE}" in
  "kali")
    qemu-system-x86_64 -accel kvm -m 4G -smp 2 -drive file=${DIRECTORY}/kali.qcow2,format=qcow2 -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22
    ;;
  "metasploitable")
    qemu-system-x86_64 -accel kvm -m 1G -smp 2 -drive file=${DIRECTORY}/metasploitable.qcow2,format=qcow2 -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2223-:22
    ;;
esac
